### ISSUE TITLE
Beautiful UI

### ISSUE THREAD

**Issue by araaks** [itsdotnickscott/Pandemic#5]
This is an extremely clean UI. I love it. It wasn't over complicated, and is straight forward. My only question is, looking at the list of the Player's Cards on the right side, will the list ever be longer than the screen? If so, will the user have to scroll to see all of the cards?

**Comment by itsdotnickscott** [comment]
Yes, we are planning to implement either a scroll method or some other way to show all the cards!! Thanks for your comment :)
