### ISSUE TITLE
Presentation Comment

### ISSUE THREAD

**Issue by SamWarrick6** [itsdotnickscott/Pandemic#7]
Really interested to see this finished game. I think the interface has a good layout for how much information you need to display. If the other player cards could have the green/yellow/red colors that would be helpful. Also if the player has too many cards to fit on the screen are the cards going to shrink in size or will they be able to scroll through them? Good job though!

**Comment by itsdotnickscott** [comment]
Thanks!! Your comments on the player cards are insightful and we'll definitely implement them.
